from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


class NOCPdfService:
    def generate_pdf(
        self,
        *,
        reference_no: str,
        borrower_name: str,
        loan_id: str,
        loan_type: str,
        loan_amount: float,
        closed_at: datetime | None,
        manager_name: str,
        generated_at: datetime,
    ) -> bytes:
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        top = height - 72

        pdf.setFont("Helvetica-Bold", 18)
        pdf.drawString(72, top, "MONIFY FINANCIAL SERVICES")
        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(72, top - 26, "No Objection Certificate (NOC)")

        pdf.setFont("Helvetica", 10)
        pdf.drawString(72, top - 46, f"Reference No: {reference_no}")
        pdf.drawString(72, top - 62, f"Issue Date: {generated_at.strftime('%d %b %Y')}")

        y = top - 104
        pdf.setFont("Helvetica", 11)
        lines = [
            f"This is to certify that Mr./Ms. {borrower_name} has successfully repaid",
            "the loan issued by Monify and there are no outstanding dues pending.",
            "",
            f"Loan Application ID: {loan_id}",
            f"Loan Type: {loan_type or 'N/A'}",
            f"Sanctioned Amount: Rs. {loan_amount:,.2f}",
            f"Loan Closure Date: {closed_at.strftime('%d %b %Y') if closed_at else '-'}",
            "",
            "The account is treated as closed and Monify has no objection",
            "against the borrower with respect to this loan account.",
        ]
        for line in lines:
            pdf.drawString(72, y, line)
            y -= 18

        stamp_x = width - 240
        stamp_y = 120
        pdf.rect(stamp_x, stamp_y, 150, 70, stroke=1, fill=0)
        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawCentredString(stamp_x + 75, stamp_y + 45, "MONIFY")
        pdf.drawCentredString(stamp_x + 75, stamp_y + 30, "OFFICIAL STAMP")
        pdf.setFont("Helvetica", 9)
        pdf.drawCentredString(stamp_x + 75, stamp_y + 15, generated_at.strftime("%d %b %Y"))

        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(72, 130, f"Approved By Loan Manager: {manager_name}")
        pdf.setFont("Helvetica", 9)
        pdf.drawString(72, 112, "Digitally generated by Monify LMS")

        pdf.showPage()
        pdf.save()
        return buffer.getvalue()
